defaults = {
  regionProps: {
    pellet_count: 25,
    pellet_multiplier: 1,
		friction: 0.75,
  },
  spawnerProps: {
		count: 1,
    horizontal:false,
		move_clockwise:true,
		cone_angle:45,
		direction:1,
		pattern:void 0,
		projectile_radius:void 0,
		projectile_speed:void 0,
		immune:true,
		turn_speed:2,
		shot_interval:200,
		pause_interval:0,
		pause_duration:0,
		turn_acceleration:0,
		shot_acceleration:0,
		projectile_duration:4000,
		powered:false,
		growth_multiplier:1,
		ignore_invulnerability:false,
		speed_loss:1,
		regen_loss:0.4,
		release_time:void 0,
		release_interval:4000,
		slippery_radius:165,
		slowing_radius:150,
		enlarging_radius:150,
		draining_radius:150,
		gravity_radius:150,
		radar_radius:150,
		repelling_radius:150,
		disabling_radius:150,
		toxic_radius:150,
		lava_radius:150,
		magnetic_reduction_radius:125,
		magnetic_nullification_radius:125,
		freezing_radius:100,
		quicksand_radius:150,
		barrier_radius:100,
		experience_drain_radius:150,
		reducing_radius:140,
		switch_interval:3000,
		player_detection_radius:160,
		circle_size:150,
		hard_mode:false,
		gravity:6,
		quicksand_strength:5,
		repulsion:6,
		push_direction:void 0,
  }
}