function getCreditsMenu(){
  list = [
    txt("Credits", 20), bigLine(),
    txt("EvadesYamlPlayer by PNCL (me)", 12),
    pdd(0, 6),
    txt("Original Evades.io game created by Micelee and developed by Stovoy, TheArctosJackal,", 12),
    txt("TTTruck, Meldiron, Kaluub, and PotatoNuke. Evades.io source code was used. Hero and", 12),
    txt("enemy designs are from Evades.io and its developers, as well as ability icon and", 12),
    txt("projectile art.", 12),
    btn("Link to Evades.io", null, 12, () => {window.open("https://evades.io/")}, "The aforementioned Evades.io."),
    pdd(0, 6),
    txt("Countless lines of code were taken or referenced from the Ravel Sandbox, originally", 12),
    txt("created by Ravelfett and currently maintained by DD1, Tronicality, and Sonic.exe.", 12),
    btn("Link to the Ravel Sandbox", null, 12, () => {window.open("https://pifary-dev.github.io/ravel/")}, "The aforementioned Ravel Sandbox."),
    pdd(0, 6),
    txt("Countless lines of code were taken or referenced from Sonic.exe's Region Editor. ", 12),
    btn("Link to the Region Editor", null, 12, () => {window.open("https://sonic3xe.github.io/evades-region-editor/")}, "The aforementioned Region Editor."),
    pdd(0, 6),
    txt("Map files taken from Sonic.exe's evades.io region editor, originally obtained from", 12),
    txt("Evades.io developers, and originally created by their respective authors.", 12),
    pdd(0, 6),
    txt("Special thanks to Sonic.exe for their vast knowledge of the inner workings of Evades.io", 12),
    txt("(and also creating the region editor).", 12),
    pdd(0, 6),
    txt("Special thanks to Stovoy for providing source code for some of the more unintuitive", 12),
    txt("aspects of the game.", 12),
    pdd(0, 4),
    txt("Bugfinders:", 12),
    txt("Sonic.exe", 8),
    txt("Pack", 8),
    txt("Bunny", 8),
    txt("Uitro", 8),
    txt("Xulated", 8),
    pdd(0, 4),
    txt("Accuracy maintainers:", 12),
    txt("Sonic.exe", 8),
    pdd(0, 4),
    txt("Custom hero design:", 12),
    txt("General Leporid concept by Bunny", 8),
    txt("Astral Projection by playoolku", 8),
    pdd(0, 4),
    row([txt("Vanilla region credits:", 12), btn(" ! ", null, 12, () => {}, "Unfortunately, I do not know the author of every region used in-game. I do intend to credit them. If a region is not listed here, it is not an indication that I created it.")]),
    txt("Dusty Depths by Piger and MeguclOwUn", 8),
    txt("Shifting Sands by Piger and DD1", 8),
    txt("Mysterious Mansion by PotatoNuke", 8),
    txt("Quiet Quarry by Extirpater and TTTruck", 8),
    txt("Quiet Quarry Hard by PotatoNuke", 8),
    txt("Frozen Fjord Hard by PotatoNuke", 8),
    txt("Endless Echo by PotatoNuke", 8),
    txt("Peculiar Pyramid Hard by PotatoNuke", 8),
    txt("Dangerous District Hard by PotatoNuke", 8),
    txt("Restless Ridge by Extirpater", 8),
    txt("Restless Ridge Hard by Amasterclasher, TheTroll, and DD1", 8),
    txt("Assorted Alcove by TTTruck", 8),
    txt("Glacial Gorge Hard originally by TTTruck", 8),
    txt("Catastrophic Core balanced by Raqzv", 8),
    txt("Infinite Inferno balanced by Piger", 8),
    txt("Magnetic Monopole Dipole balanced by Piger", 8),
    txt("Magnetic Monopole Dipole Hard balanced by Piger", 8),
    txt("Burning Bunker Hard balanced by Piger", 8),
    txt("Glacial Gorge Hard balanced by Raqzv and Piger", 8),
    txt("Other maps created by Evades.io developers or dedicated Evades.io community members.", 8),
    pdd(0, 3000),
    txt("Shoutout to gloglonzo", 8),
  ]
  return list;
}